CREATE DATABASE SRC;
USE SRC;

CREATE TABLE Autos(
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()) NOT NULL,
    Brand VARCHAR(50) NOT NULL,
    Model VARCHAR(50) NOT NULL,
    Class VARCHAR(20) NOT NULL,  
    GearboxType VARCHAR(20) NOT NULL, 
    Color VARCHAR(20) NOT NULL,
    DailyPrice DECIMAL(10,2) NOT NULL
);

CREATE TABLE Clients (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Phone VARCHAR(20) UNIQUE NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    DriverLicense VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE Employees (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Position VARCHAR(50) NOT NULL,
    Phone VARCHAR(20) UNIQUE NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Rentals (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()) NOT NULL,
    AutoId CHAR(36) NOT NULL,
    CustomerId CHAR(36) NOT NULL,
    EmployeeId CHAR(36) NOT NULL,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NOT NULL,
    TotalPrice DECIMAL(10,2) NOT NULL,
    Status ENUM('Active', 'Completed', 'Cancelled') DEFAULT 'Active',
    FOREIGN KEY (AutoId) REFERENCES Autos(Id),
    FOREIGN KEY (CustomerId) REFERENCES Customers(Id),
    FOREIGN KEY (EmployeeId) REFERENCES Employees(Id)
);

CREATE TABLE Users (
    Id CHAR(36) PRIMARY KEY DEFAULT (UUID()) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL, 
    Role ENUM('Customer', 'Employee', 'Admin') NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE Customers ADD COLUMN UserId CHAR(36) UNIQUE NULL;
ALTER TABLE Customers ADD CONSTRAINT fk_customer_user FOREIGN KEY (UserId) REFERENCES Users(Id);

ALTER TABLE Employees ADD COLUMN UserId CHAR(36) UNIQUE NULL;
ALTER TABLE Employees ADD CONSTRAINT fk_employee_user FOREIGN KEY (UserId) REFERENCES Users(Id);